/run/initialize

/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 0
# Use General Particle Source
/gps/particle neutron

# Mono energy
/gps/ene/type Mono
/gps/ene/mono 6000 keV
/gps/time 0 ns
# Position distribution (point source at origin)
/gps/pos/type Point
/gps/pos/centre -20 0 0 cm

# Isotropic emission
#/gps/ang/type iso

# Beam emission
/gps/direction 1 0 0


# Generate events
/run/beamOn 10000000